apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-app
spec:
  selector:
    matchLabels:
      app: listener-app
  template:
    metadata:
      labels:
        app: listener-app
    spec:
      containers:
        - name: listener-app
          image: papaya147/listener-service:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: listener-service
spec:
  selector:
    app: listener-service
  ports:
    - protocol: TCP
      name: listener-port
      port: 80
      targetPort: 80
